# 使用官方 Node.js 18 镜像作为基础镜像
FROM node:18-slim

# 更新系统并安装 Chromium
RUN apt-get update && apt-get install -y \
    chromium \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# 设置 Puppeteer 使用系统安装的 Chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV PUPPETEER_EXECUTABLE_PATH /usr/bin/chromium

# 设置工作目录
WORKDIR /usr/src/app

# 复制 package.json 和 package-lock.json（如果存在）
COPY package*.json ./
COPY config.local.js ./

# 安装项目依赖
RUN npm install

# 复制项目文件到工作目录
COPY . .

# 暴露应用程序运行的端口（根据您的应用程序配置进行调整）
EXPOSE 5757

# 定义环境变量
ENV NODE_ENV=production

# 运行应用程序
CMD [ "npm", "run", "start" ]
