# 使用官方 Puppeteer 镜像作为基础镜像
FROM node:20-bullseye-slim

# 验证 Node.js 和 npm 安装
RUN apt-get update && apt-get install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2 libpangocairo-1.0-0 &&\
  groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser

  # 设置工作目录
WORKDIR /home/pptruser/mini-form

RUN chown -R pptruser:pptruser /home/pptruser/
USER pptruser

# 声明数据卷
VOLUME ["/home/pptruser/mini-form/attachment", "/home/pptruser/mini-form/uploads"]

# 复制 package.json
COPY package.json ./
COPY config.prod.js ./
# 安装项目依赖
RUN npm install
# RUN npx @puppeteer/browsers install chrome@stable
# 复制项目文件到工作目录
COPY . .
# 暴露应用程序运行的端口
EXPOSE 5757

# 定义环境变量
ENV NODE_ENV=production
# 运行应用程序
CMD [ "npm", "run", "start" ]